# -*- coding: utf-8 -*-
"""ML LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-aVDpsTM9JUIKQsBX45ATpeUqnBFw_w
"""

import numpy as np

np.random.seed(42)

x = 2 * np.random.rand(100, 1)

y = 4 + 3 * x + np.random.randn(100,1)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

from sklearn.linear_model import LinearRegression

model =LinearRegression()

model.fit(x_train, y_train)

print (model.intercept_)
print (model.coef_)

score = model.score(x_test, y_test)

print(score)

